---

# Configuración de Travis CI
# --------------------------------------

# [Travis CI] http://travis-ci.org
# [configuración] http://about.travis-ci.org/docs/user/build-configuration/


language: python  # Necesario para ejecutar Ansible

python: "2.7"

before_install:
  # Nos aseguramos de que todo está actualizado.
  - sudo apt-get update -qq

install:
  - pip install ansible

  # Añadimos ansible.cfg para poner el path de los roles.
  - sudo printf "[defaults]\nroles_path = ../" > ansible.cfg

script:
  # Comprobamos la sintáxis del role/playbook.
  - "ansible-playbook -i tests/inventory tests/test.yml --syntax-check"

  # Ejecutamos el role/playbook con ansible-playbook
  - "ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo"

  # Ejecutamos el role/playbook de nuevo, asegurándonos de que es idempotent.
  - "ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo | grep -q 'changed=0.*failed=0' && (echo 'Test Idempotence: pasado' && exit 0) || (echo 'Test Idempotence: fallo' && exit 1)"

  # Notificamos del estado a Galaxy
notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/